### PR TITLE
Update gradle.properties to latest

### PR DESCRIPTION
**Pull request by amusingimpala75**
Silly me, I forgot that I had fixed an error regarding Mixin Entity Hooks for Dimensions when updating to latest. So back it is.

### CODE REVIEW

**Comment by amusingimpala75** [comment]
I had forgotten to migrate the mappings, not just change the name.

**Comment by amusingimpala75** [comment]
One of these times I'll get it right. I think that is this time

**Comment by amusingimpala75** [comment]
Wait, I'm getting errors.

**Comment by amusingimpala75** [comment]
Turns out REI was causing the " Mixin apply failed fabric-dimensions-v1.mixins.json:EntityHooks" errors, so I upped the version

**Comment by Andrews54757** [comment]
Bumped versions in https://github.com/Andrews54757/OptiFabric-updated/commit/6649d97a63487a95243076be50b938989dd39e3f

**Pull request closed without merging**
